<div class="form-group wax-element wax-text wax-autocomplete <?=$this->getClass()?> <?=$this->hasError()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>
	<?=$this->getPrefix()?>
	<input type="text" class="form-control" id="<?=$this->getId()?>" name="<?=$this->getName()?>[display]" value="<?=$this->getValue('display')?>" <?=$this->getPlaceholder()?> <?=$this->getAdditionalAttributes()?> />
	<input type="hidden" id="<?=$this->getId()?>-value" name="<?=$this->getName()?>[value]" value="<?=$this->getValue('value')?>" />
	<input type="hidden" id="<?=$this->getId()?>-new" name="<?=$this->getName()?>[new]" value="<?=$this->getValue('new')?>" />
	<?=$this->getSuffix()?>
	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<?=$this->fetchJavascript()?>

<?=$this->fetchJavascript('validator.phtml')?>

<?php

// About Bloodhound suggestion engine:
// https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md
//
// Showing values from assoc arrays:
// http://stackoverflow.com/questions/21895025/use-different-value-from-json-data-instead-of-displaykey-using-typeahead

/*
	
	For later CSS, scrolling:

	#scrollable-dropdown-menu .tt-dropdown-menu {
	  max-height: 150px;
	  overflow-y: auto;
	}
*/
