<div class="form-group wax-element wax-checkboxgroup <?=$this->getClass()?> <?=$this->hasError()?>" id="<?=$this->getId()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>
	<? foreach ($this->getItems() as $value => $label): ?>
		<div class="checkbox wax-element wax-checkbox">
			<label>
				<input type="checkbox" name="<?=$this->getName()?>" value="<?=$value?>" <?=$this->getAdditionalAttributes($value)?> /> <?=$label?>
			</label>
		</div>
	<? endforeach; ?>
	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<?=$this->fetchJavascript('validator.phtml')?>