<div class="form-group wx-element wx-checkbox <?=$this->getClass()?> <?=$this->hasError()?>" <?=$this->getData()?>>
	<div class="checkbox">
		<label>
			<input type="checkbox" id="<?=$this->getId()?>" name="<?=$this->getName()?>" value="<?=$this->getValue()?>" <?=$this->getAdditionalAttributes()?> /> <?=$this->getLabel()?>
		</label>
	</div>
	<?=$this->fetchTemplate('info')?>
	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<?=$this->fetchJavascript('validator.phtml')?>