<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getElements(), 'hideSelector' => '.wx-element'))?>
<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getColumns(), 'hideSelector' => '.wx-column'))?>
<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getRows(), 'hideSelector' => '.wx-row'))?>
<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getBcolumns(), 'hideSelector' => '.wx-bcolumn'))?>
<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getBrows(), 'hideSelector' => '.wx-brow'))?>
<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getSections(), 'hideSelector' => '.wx-section'))?>