<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getElements(), 'hideSelector' => '.wax-element'))?>
<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getColumns(), 'hideSelector' => '.wax-column'))?>
<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getRows(), 'hideSelector' => '.wax-row'))?>
<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getBcolumns(), 'hideSelector' => '.wax-bcolumn'))?>
<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getBrows(), 'hideSelector' => '.wax-brow'))?>
<?=$this->fetchJavascript('condition.phtml', array('elements' => $this->getSections(), 'hideSelector' => '.wax-section'))?>