<? foreach ($this->getInstances() as $language): ?>

<div class="<?=$this->getClass()?> form-group wax-element wax-file <?=$this->hasError()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>

	<div id="<?=$this->getId($language)?>-previews" class="file-previews">
		<? if (!empty($this->getValue(false, $language))): ?>
			<div class="file">
				<a href="" class="remove"><span class="fa fa-remove"></a><a href="<?=$this->getFileUrl($language)?>" target="_blank" class="name"><?=$this->getValue(false, $language)?></a>
			</div>
		<? endif; ?>
	</div>
	<input type="hidden" class="value" value="<?=$this->getValue(false, $language)?>" name="<?=$this->getName(true, $language)?>" <?=$this->getAdditionalAttributes($language)?> />

	<div class="file-uploader-container">
		<div class="dropzone" id="<?=$this->getId($language)?>"></div>
		<div id="<?=$this->getId($language)?>-progress" class="progress hidden"><div class="bar"></div></div>
	</div>

	<div class="dropzone-previews" style="display: none;"></div>

	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<?=$this->fetchJavascript(null, array('language' => $language))?>

<? endforeach; ?>

<?=$this->fetchJavascript('validator.phtml')?>