<div class="form-group wax-element wax-multiselect <?=$this->getClass()?> <?=$this->hasError()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>
	<select class="form-control" id="<?=$this->getId()?>" name="<?=$this->getName()?>" multiple="true" <?=$this->getAdditionalAttributes()?>>
		<? foreach ($this->getItems() as $key => $item): ?>
			<? if (is_array($item)): ?>
				<optgroup label="<?=$item['label']?>">
					<? foreach ($item['items'] as $value => $label): ?>
						<option value="<?=$value?>" <?=$this->getSelected($value, true)?>> <?=$label?> </option>
					<? endforeach; ?>
				</optgroup>
			<? else: ?>
				<option value="<?=$key?>" label="<?=$item?>" <?=$this->getSelected($key, true)?>> <?=$item?> </option>
			<? endif; ?>
		<? endforeach; ?>
	</select>
	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<?=$this->fetchJavascript('validator.phtml')?>