<div class="form-group wax-element wax-text wax-password <?=$this->getClass()?> <?=$this->hasError()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>
	<?=$this->getPrefix()?>
	<input type="password" class="form-control" id="<?=$this->getId()?>" name="<?=$this->getName()?>" <?=$this->getPlaceholder()?> value="<?=$this->getLoadedValue()?>" <?=$this->getAdditionalAttributes()?> />
	<?=$this->getSuffix()?>
	<? if ($this->canShowPassword()): ?>
		<a href="" class="wax-show-password"><span class="<?=$this->getShowPasswordIcon()?>"></span></a>
	<? endif; ?>
	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<?=$this->fetchJavascript()?>
<?=$this->fetchJavascript('validator.phtml')?>