<div class="form-group wx-element wx-text wx-password <?=$this->getClass()?> <?=$this->hasError()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>
	<?=$this->fetchTemplate('info')?>
	<?=$this->getPrefix()?>
	<input type="password" class="form-control" id="<?=$this->getId()?>" name="<?=$this->getName()?>" <?=$this->getPlaceholder()?> value="<?=$this->getValue()?>" <?=$this->getAdditionalAttributes()?> />
	<?=$this->getSuffix()?>
	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<?=$this->fetchJavascript('validator.phtml')?>