<div class="form-group wax-element wax-radio <?=$this->getClass()?> <?=$this->hasError()?>" <?=$this->getData()?>>
	<div class="radio">
		<label>
			<input type="radio" id="<?=$this->getId()?>" name="<?=$this->getName()?>" value="<?=$this->getValue()?>" <?=$this->getAdditionalAttributes()?> /> <?=$this->getLabel()?>
		</label>
	</div>
	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<?=$this->fetchJavascript('validator.phtml')?>