<div class="form-group wax-element wax-radiogroup <?=$this->getClass()?> <?=$this->hasError()?>" id="<?=$this->getId()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>
	<? foreach ($this->getItems() as $value => $label): ?>
		<div class="radio wax-element wax-radio">
			<label>
				<input type="radio" name="<?=$this->getName()?>" value="<?=$value?>" <?=$this->getAdditionalAttributes($value)?> /> <?=$label?>
			</label>
		</div>
	<? endforeach; ?>
	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<?=$this->fetchJavascript()?>

<?=$this->fetchJavascript('validator.phtml')?>