<div class="form-group wax-element wax-select <?=$this->getClass()?> <?=$this->hasError()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>
	<?=$this->getPrefix()?>
	<select class="form-control" id="<?=$this->getId()?>" name="<?=$this->getName()?>" <?=$this->getPlaceholder()?> <?=$this->getAdditionalAttributes()?> <?=$this->getMultiple()?> <?=$this->getSearch()?>>
		<? foreach ($this->getItems() as $key => $item): ?>
			<? if (is_array($item)): ?>
				<optgroup label="<?=$item['label']?>">
					<? foreach ($item['items'] as $value => $label): ?>
						<option value="<?=$value?>" <?=$this->getSelected($value, true)?><?=$this->getIcon($key)?>> <?=$label?> </option>
					<? endforeach; ?>
				</optgroup>
			<? else: ?>
				<option value="<?=$key?>" label="<?=$item?>" <?=$this->getSelected($key, true)?><?=$this->getIcon($key)?>> <?=$item?> </option>
			<? endif; ?>
		<? endforeach; ?>
	</select>
	<?=$this->getSuffix()?>
	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<?=$this->fetchJavascript()?>

<?=$this->fetchJavascript('validator.phtml')?>