<? foreach ($this->getInstances() as $language): ?>

<div class="<?=$this->getClass()?> form-group wx-element wx-text <?=$this->hasError()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>
	<?=$this->fetchTemplate('info')?>

	<?=$this->getPrefix()?>
	<input type="text" class="form-control" id="<?=$this->getId($language)?>" name="<?=$this->getName(true, $language)?>" <?=$this->getPlaceholder()?> value="<?=$this->getValue(false, $language)?>" <?=$this->getAdditionalAttributes($language)?> />
	<?=$this->getSuffix()?>

	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<? endforeach; ?>

<?=$this->fetchJavascript('validator.phtml')?>
