<? foreach ($this->getInstances() as $language): ?>

<div class="<?=$this->getClass()?> form-group wax-element wax-text <?=$this->hasError()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>

	<?=$this->getPrefix()?>
	<input type="text" class="form-control" id="<?=$this->getId($language)?>" name="<?=$this->getName(true, $language)?>" <?=$this->getPlaceholder()?> value="<?=$this->getValue(false, $language)?>" <?=$this->getAdditionalAttributes($language)?> />
	<?=$this->getSuffix()?>
	<?=($language?'<span class="language-indicator">'.$language.'</span>':'')?>

	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error', array('language' => $language))?>
</div>

<? endforeach; ?>

<?=$this->fetchJavascript('validator.phtml')?>
