<? foreach ($this->getInstances() as $language): ?>

<div class="form-group wx-element wx-textarea <?=$this->getClass()?> <?=$this->hasError()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>
	<?=$this->fetchTemplate('info')?>
	<?=$this->getPrefix()?>
	<textarea class="form-control" id="<?=$this->getId($language)?>" name="<?=$this->getName(true, $language)?>" <?=$this->getPlaceholder()?> <?=$this->getAdditionalAttributes($language)?>><?=$this->getValue(false, $language)?></textarea>
	<?=$this->getSuffix()?>
	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error')?>
</div>

<? endforeach; ?>

<?=$this->fetchJavascript('validator.phtml')?>