<? foreach ($this->getInstances() as $language): ?>

<div class="form-group wax-element wax-textarea <?=$this->getClass()?> <?=$this->hasError()?>" <?=$this->getData()?>>
	<?=$this->fetchTemplate('label')?>
	<?=$this->getPrefix()?>
	<textarea class="form-control" id="<?=$this->getId($language)?>" name="<?=$this->getName(true, $language)?>" <?=$this->getPlaceholder()?> <?=$this->getAdditionalAttributes($language)?>><?=$this->getValue(false, $language)?></textarea>
	<?=$this->getSuffix()?>
	<?=($language?'<span class="language-indicator">'.$language.'</span>':'')?>
	<?=$this->fetchTemplate('description')?>
	<?=$this->fetchTemplate('error', array('language' => $language))?>
</div>

<? endforeach; ?>

<?=$this->fetchJavascript(null, array('language' => $language))?>

<?=$this->fetchJavascript('validator.phtml')?>