<? $this->scriptCaptureStart(); ?>
	$(function(){
		waxform.autocomplete({
			form: '#<?=$this->formIdentifier?>',
			fieldId: '<?=$this->getId()?>',
			fieldName: '<?=$this->getName()?>',
			fieldPlainName: '<?=$this->getName(false)?>',
			display: '<?=$this->getDisplay()?>',
			mode: '<?=$this->getMode()?>',
			isKeyAsValue: <?=$this->isKeyAsValue() ? true : false?>,
			hint: <?=$this->hint?>,
			highlight: <?=$this->highlight?>,
			minLength: <?=$this->minLength?>,
			limit: <?=$this->getLimit()?>,
			emptyHtml: '<?=$this->getEmptyHtml()?>',
			suggestionHtml: '<?=$this->getSuggestionHtml()?>',
			<? if ($this->getOnSelect()): ?>
				onSelect: <?=$this->getOnSelect()?>,
			<? endif; ?>
			<? if ($this->getMode() == 'local'): ?>
				local: [<? foreach ($this->convertItemsToAutocompleteFormat($this->getItems()) as $key => $value): ?>{autocompletekey : <?=$key?>,<? foreach ($value as $vkey => $vvalue): ?><?=$vkey?> : "<?=$vvalue?>",<? endforeach; ?>},<? endforeach; ?>],
			<? endif; ?>
			<? if ($this->hasDynamicParams()): ?>
				dynamicParams: {
					<? foreach ($this->getDynamicParams() as $param): ?>
						<?=$param['name']?> : '<?=$param["selector"]?>',
					<? endforeach; ?>
				},
			<? endif; ?>
			<? if ($this->isDefaults() && $this->getMode() != 'remote'): ?>
				itemsSync: [<? $i = 1; foreach ($this->convertItemsToAutocompleteFormat($this->getItems()) as $value): ?>'<?=strtolower($value[$this->getDisplay()])?>'<?=count($this->getItems()) == $i ? '' : ','?><? $i++; ?><? endforeach; ?>],
			<? endif; ?>
		});
	})

<? $this->scriptCaptureEnd('PREPEND'); ?>