<? $hasConditional = false; foreach ($elements as $key => $element): ?>
	<? if ($element->hasCondition()) { $hasConditional = true; } ?>
<? endforeach; ?>

<? if ($hasConditional): ?>
	<? $this->scriptCaptureStart(); ?>
		$(function(){
			<? foreach ($elements as $key => $element): ?>
				<? if ($element->hasCondition()): ?>

					<? foreach ($element->condition as $field => $value): ?>
						<? 
							if (is_array($value)):
								$jsValue = '[' . implode(',', $value) . ']';
							elseif (is_bool($value)):
								$jsValue = $value ? 'true' : 'false';
							else:
								$jsValue = "'" . $value . "'";
							endif;
						?>

						waxform.addCondition({
							form: '#<?=$element->formIdentifier?>',
							conditionFieldName: '<?=$field?>',
							targetFieldName: '<?=method_exists($element,'getName') ? $element->getName() : ""?>',
							targetFieldId: '<?=method_exists($element,'getId') ? $element->getId() : ""?>',
							nth: '<?=$element->getNthInstance()?>',
							cleanId: '<?=$element->getCleanId()?>',
							hideSelector: '<?=$hideSelector?>',
							type: '<?=$element->getType()?>',
							isValueArray: <?=is_array($value) ? 'true' : 'false'?>,
							value: <?=$jsValue?>,
							isOriginal: <?=method_exists($element, 'isOriginal') && !$element->isOriginal() ? 'false' : 'true'?>
						});
					<? endforeach; ?>
				<? endif; ?>
			<? endforeach; ?>
		})
	<? $this->scriptCaptureEnd('PREPEND'); ?>
<? endif; ?>