<? $this->scriptCaptureStart(); ?>
	$(function(){
		waxform.file({
			form: '#<?=$this->formIdentifier?>',
			fieldId: '<?=$this->getId($language)?>',
			fieldName: '<?=$this->getName(true, $language)?>',
			fieldPlainName: '<?=$this->getName(false)?>',
			maxFilesize: <?=$this->getMaxFileSize()?>,
			acceptedFiles: '<?=$this->getAcceptedFiles()?>',
			dictDefaultMessage: '<?=$this->getButtonLabel()?>',
		});
	})
<? $this->scriptCaptureEnd('PREPEND'); ?>