<? if ($this->isInit()): ?>
	<? $this->scriptCaptureStart(); ?>
		$(function() {
			$('#<?=$this->getId()?>').wxform();
		})

		<? foreach ($this->getInitScripts() as $one): ?>
			executeFunctionByName('<?=$one['script']?>', window, <?=json_encode($one['data'])?>)
		<? endforeach; ?>
	<? $this->scriptCaptureEnd('PREPEND'); ?>
<? endif; ?>

<? if ($this->getSubmit()): ?>
	<? $this->scriptCaptureStart(); ?>
		$(function() {
			$('<?=$this->getSubmit()?>').unbind('click').click(function(e){
				e.preventDefault();
				$('#<?=$this->getId()?>').data('formValidation').validate();
			});
		})
	<? $this->scriptCaptureEnd('PREPEND'); ?>
<? endif; ?>