<? $this->scriptCaptureStart(); ?>
	$(function(){
		waxform.image({
			form: '#<?=$this->formIdentifier?>',
			fieldId: '<?=$this->getId()?>',
			fieldName: '<?=$this->getName()?>',
			fieldPlainName: '<?=$this->getName(false)?>',
			maxFilesize: <?=$this->getMaxFileSize()?>,
			acceptedFiles: '<?=$this->getAcceptedFiles()?>',
			dictDefaultMessage: '<?=$this->getButtonLabel()?>',
			imageUrlBase: '<?=$this->getImageUrlBase()?>',
			onSuccess: '<?=$this->getOnSuccess()?>',
			onRemove: '<?=$this->getOnRemove()?>',
		});
	})
<? $this->scriptCaptureEnd('PREPEND'); ?>