<? $this->scriptCaptureStart(); ?>
	$(function(){
		waxform.multifile({
			form: '#<?=$this->formIdentifier?>',
			fieldId: '<?=$this->getId($language)?>',
			fieldName: '<?=$this->getName(true, $language)?>',
			fieldPlainName: '<?=$this->getName(false)?>',
			maxFilesize: <?=$this->getMaxFileSize()?>,
			acceptedFiles: '<?=$this->getAcceptedFiles()?>',
			dictDefaultMessage: '<?=$this->getButtonLabel()?>',
			fileUrlBase: '<?=$this->getFileUrlBase()?>',
			<? if ($this->hasLimit()): ?>
				maxFiles: <?=$this->getLimit()?>
			<? endif; ?>
			<? if ($this->hasFields()): ?>
				fields: [
					<? foreach ($this->getFields() as $key => $one): ?>
						{name: '<?=$one["name"]?>', placeholder: '<?=$one["placeholder"]?>', type: '<?=isset($one["type"])?$one["type"]:""?>'},
					<? endforeach; ?>
				]
			<? endif; ?>
		});
	})
<? $this->scriptCaptureEnd('PREPEND'); ?>