<? $this->scriptCaptureStart(); ?>
	$(function(){
		waxform.multiimage({
			form: '#<?=$this->formIdentifier?>',
			fieldId: '<?=$this->getId()?>',
			fieldName: '<?=$this->getName()?>',
			fieldPlainName: '<?=$this->getName(false)?>',
			maxFilesize: <?=$this->getMaxFileSize()?>,
			acceptedFiles: '<?=$this->getAcceptedFiles()?>',
			dictDefaultMessage: '<?=$this->getButtonLabel()?>',
			previewUrlBase: '<?=$this->getPreviewUrlBase()?>',
			thumbnailUrlBase: '<?=$this->getThumbnailUrlBase()?>',
			<? if ($this->hasLimit()): ?>
				maxFiles: <?=$this->getLimit()?>
			<? endif; ?>
			<? if ($this->hasFields()): ?>
				fields: {
					<? foreach ($this->getFields() as $key => $one): ?>
						{name: '<?=$one["name"]?>', placeholder: '<?=$one["placeholder"]?>'}
					<? endforeach; ?>
				}
			<? endif; ?>
		});
	})
<? $this->scriptCaptureEnd('PREPEND'); ?>