<? $this->scriptCaptureStart(); ?>
	$(function() {
		<? if (!$this->isOriginal()): ?>
			waxform.bootstrapSelect({
				form: '#<?=$this->formIdentifier?>',
				fieldName: '<?=$this->getName()?>'
			})
		<? endif; ?>

		<? foreach ($this->getElementsByConditionalSourceParamName($this->getName(false), 'select') as $element): $element->setNthInstance($this->getNthInstance()); ?>
			<? if ($element->hasDynamicParams()): ?>
				waxform.select({
					form: '#<?=$this->formIdentifier?>',
					fieldId: '<?=$this->getId()?>',
					fieldName: '<?=$element->getName()?>',
					fieldPlainName: '<?=$element->getName(false)?>',
					isOriginal: <?=$element->isOriginal() ? 'true' : 'false'?>,
					params: ["<?=implode('\",\"',$element->getDynamicParams())?>"]
				});
			<? endif; ?>
		<? endforeach; ?>
	})
<? $this->scriptCaptureEnd('PREPEND'); ?>