<? $this->scriptCaptureStart(); ?>
	$(function(){
		waxform.slider({
			fieldId: '<?=$this->getId()?>',
			fieldName: '<?=$this->getName()?>',
			min: <?=$this->min?>,
			max: <?=$this->max?>,
			step: <?=$this->step?>,
			tooltip : '<?=$this->tooltip ? 'show' : 'hide'?>',
			orientation : '<?=$this->orientation?>',
			enabled : <?=($this->getDisabled() === false ? 'true' : 'false')?>,
			range: <?=$this->range === true ? 'true' : 'false'?>,
			<? if (!empty($this->getValueString())): ?>
				value : <?=$this->getValueString()?>,
			<? endif; ?>
			<? if (is_array($this->getValue())): ?>
				values: {<? $i=0; foreach($this->getValue() as $key => $value): $i++; ?><?=$key?>:"<?=$value?>"<?=(count($this->getValue())>$i?',':'')?><?endforeach;?>},
			<? endif; ?>
			<? if ($this->minSelector !== null): ?>
				minSelector: '<?=$this->getMinSelector()?>',
			<? endif; ?>
			<? if ($this->maxSelector !== null): ?>
				maxSelector: '<?=$this->getMaxSelector()?>',
			<? endif; ?>
		});
	})
<? $this->scriptCaptureEnd('PREPEND'); ?>