<? $this->scriptCaptureStart(); ?>
	$(function(){
		waxform.tags({
			id: '<?=$this->getId()?>',
			form: '#<?=$this->formIdentifier?>',
			fieldName: '<?=$this->getName()?>',
			freeInput: <?=$this->isFreeInput() ? 'true' : 'false'?>,
			<? if ($this->isFreeInput()): ?>
				items: [<? foreach ($this->getItems() as $key => $item): ?>"<?=addslashes($item)?>",<? endforeach; ?>],
				values: [<? foreach ($this->getValueArray() as $id => $text): ?>"<?=addslashes($text)?>",<? endforeach; ?>],
			<? else: ?>
				items: [<? foreach ($this->getItems() as $key => $item): ?>{"id":"<?=$key?>","text":"<?=addslashes($item)?>"},<? endforeach; ?>],
				values: [<? foreach ($this->getValueArray() as $id => $text): ?>{"id":"<?=$id?>","text":"<?=addslashes($text)?>"},<? endforeach; ?>],
			<? endif; ?>
		});
	})
<? $this->scriptCaptureEnd('PREPEND'); ?>